### ISSUE TITLE
Document how to use capturing in email forwards

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-support#158]
Mailgun allows capturing output and then using that in the recipient for the forwarding. I propose writing an article on this.

**Comment by weppos** [comment]
We had a similar conversation in the past, and the idea was to not promote it as that will make us dependent to a specific service implementation.

In fact, if we should ever consider extra optimizations (such as merging different emails together with a | to reduce the # of routes), we will possibly break this feature.

I still believe we should not rely on the assumption that this possibility exists, as a simple mail forward.

**Comment by aeden** [comment]
Not going to do this for now.
