### ISSUE TITLE
Section about interacting with the API

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-support#172]
There are several things that we should write about:
- Finding tokens, the differences between them and what API version they can be used for.
- Adding and managing applications for development purposes.
- Revoking OAuth authorizations.

**Comment by jacegu** [comment]
@sbastn for some reason I think you did some work on this but I cannot find it here... Did you or I imagined it?

**Comment by sbastn** [comment]
@jacegu I don't think it was me. Sorry.

**Comment by kayla-broussard** [comment]
@jacegu In my effort to try to remove the backlog of issues - does this article take care of your first point? https://support.dnsimple.com/articles/api-access-token/

**Comment by jacegu** [comment]
Yes, it does.
