### ISSUE TITLE
Add notes about transfer rules

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-support#180]
In https://support.dnsimple.com/articles/requesting-transfer-code/ , add some notes about the 60 day transfer rule, whois privacy protection, and anything else that might impact a customer's ability to transfer a domain out.

**Comment by aeden** [comment]
Updating the location of this article: https://support.dnsimple.com/articles/transferring-domain-away/

**Comment by onlyhavecans** [comment]
I added a warning in this PR about the 60 day. is there more that should be lopped in as a section?
https://github.com/dnsimple/dnsimple-support/pull/253

**Comment by weppos** [comment]
We can consider it closed @onlyhavecans
