### ISSUE TITLE
Request: doc about custom domains + Github Pages + SSL

### ISSUE THREAD

**Issue by kevinSuttle** [dnsimple/dnsimple-support#198]
Thanks!

**Comment by jacegu** [comment]
Thanks for the suggestion @kevinSuttle 

We currently have [an article](https://support.dnsimple.com/articles/github-pages/) about integrating DNSimple and GitHub Pages. Unfortunately it looks like GitHub does not support custom domains and SSL: it's [only supported if you use the original `github.io` domain](https://github.com/blog/2186-https-for-github-pages). We will update the article to reflect this.

Is there anything we are missing?

**Comment by kevinSuttle** [comment]
Nope that looks good to me. Thanks.
