### ISSUE TITLE
Article about creating a user access token

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-support#201]
Write an article explaining how to generate a user access token.

**Comment by aeden** [comment]
Possibly connected to https://github.com/dnsimple/dnsimple-support/issues/172

**Comment by aeden** [comment]
Existing article: https://support.dnsimple.com/articles/api-access-token/

**Comment by kayla-broussard** [comment]
Resolved with PR https://github.com/dnsimple/dnsimple-support/pull/559
