### ISSUE TITLE
Articles about adding specific record types

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-support#232]
It sounds silly, but simple articles like:

- How to add an A record.
- How to add a CNAME record.
- How to add an ALIAS record.
- How to add MX records.

Might be helpful.

**Comment by weppos** [comment]
@aeden I made a few commits in preparation in dnsimple/dnsimple-support#239. While working on the PR I noticed that some record articles have proper instructions, for example https://support.dnsimple.com/articles/url-record/

Others only have the "Add".

I wonder, should we have one article per action? Example:

- Add an A record
- Update an A record
- etc

or instead should we perhaps add the following articles:

- Add, Update, and Remove A record
- Add, Update, and Remove CNAME record

(or)

- Manage A record
- Manage URL record

I also propose to link them from the "What is XXX record" articles.

**Comment by aeden** [comment]
I think we should start with one article per type for now. So, for example, "How to Add, Update, and Remove A Records".
