### ISSUE TITLE
Take away deadline for Gold customer to make changes

### ISSUE THREAD

**Issue by Barbamama** [dnsimple/dnsimple-support#243]
This issue is to remove the last sentence of the paragraphe related to the deadline of June 2016
https://support.dnsimple.com/articles/new-plans-for-gold/

As an existing Gold customer, you do not need to make any changes today. Please take away this:
You can continue using your current plan until at least the end of June, 2016.

**Comment by weppos** [comment]
It says _until at least the end of June_, therefore it's not incorrect. It means that at least until June 2016 you can keep that plan, potentially even after.

We can adjust the date.

Also note that if any change is made to that article, it must be replicated to all corresponding articles in https://support.dnsimple.com/categories/account/ (e.g. Platinum, Silver, etc).

**Comment by onlyhavecans** [comment]
Looks like @aeden did this today https://github.com/dnsimple/dnsimple-support/commit/f95eea2b432daea54e28eb131f8452fe0001b458
