### ISSUE TITLE
Add reference to the API 3 days course in the API article

### ISSUE THREAD

**Issue by Barbamama** [dnsimple/dnsimple-support#244]
This issue is to add the link to the API 3 days course to the API article.  Here is the link of the support doc page. 
https://support.dnsimple.com/categories/api/

**Comment by onlyhavecans** [comment]
What's the link to the API 3 days course? Is there a quick link to how to view it to use specifically for the support site?

**Comment by weppos** [comment]
@Barbamama https://support.dnsimple.com/categories/api/ is not an article, rather a category. Sadly, we can't easily customize category templates.

Please let me know how the link will look like, what is the code required, and if there is a specific article where you think it would make sense to add it.

**Comment by weppos** [comment]
Closing the issue in agreement with @laetitiaeden
