### ISSUE TITLE
Duplicate search bar

### ISSUE THREAD

**Issue by OleMchls** [dnsimple/dnsimple-support#273]
When visiting the support page a customer is presented with two search bars, I even can't tell if there are differences. We should tidy this up a bit :)

![screen shot 2017-03-31 at 11 41 30](https://cloud.githubusercontent.com/assets/584259/24545318/080fc3e2-1607-11e7-9096-7c3b294eb1ec.png)

**Comment by weppos** [comment]
@sbastn @doctoraw thoughts?
