### ISSUE TITLE
Definition of secondary DNS not in FAQ

### ISSUE THREAD

**Issue by Barbamama** [dnsimple/dnsimple-support#277]
In the support document regarding secondary DNS (https://support.dnsimple.com/articles/secondary-dns/) I feel that it's missing the definition of what secondary DNS is, especially in the FAQ section. I think it's important to explain what it does and why we offer it.

**Comment by onlyhavecans** [comment]
I popped this one out real quick since I think I had a good answer. Pinging @aeden and @weppos for a review on it.
