### ISSUE TITLE
Help transferring in a pre-google domains google-enom domain

### ISSUE THREAD

**Issue by onlyhavecans** [dnsimple/dnsimple-support#279]
A user wrote in having trouble getting access to and transferring in a pre-google domains google-enom domain. Normally a user does not have access to the registry. Working them through it they found this article and recommended we create a version specifically for transfering from this into DNSimple.

https://at.godaddy.com/help/transferring-a-google-registered-enom-domain-to-us-8827

**Comment by weppos** [comment]
I'm not sure how this applies to us as I'm not aware of Google registered Enom domain. I'm closing for now as I can't actually get to the original conversation. Should we have a precise issue to document we can write a specific article.
