### ISSUE TITLE
XXX special policies

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#290]
The XXX TLD requires a _Member Auth Token_ to be provided in order to activate the domain.

You can provide the token during the registration, as extended attribute:

![screen shot 2017-08-15 at 11 51 56](https://user-images.githubusercontent.com/5387/29310996-4db8a340-81b0-11e7-8d83-52ea56e63a75.png)

For API, you need to pass those information as extended attributes. We pass those information in the extended attribute API for the XXX, but apparently they are optional, hence users may create a domain without passing that information.

```
curl -X GET \
  https://api.dnsimple.com/v2/tlds/xxx/extended_attributes \
  -H 'accept: application/json' \
  -H 'authorization: Bearer TOKEN' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json'
```

```json
{
    "data": [
        {
            "name": "xxx_memberid",
            "description": "Member Authorization Token",
            "required": false,
            "options": []
        },
        {
            "name": "xxx_resolving",
            "description": "Website Resolves",
            "required": false,
            "options": [
                {
                    "title": "Yes",
                    "value": "1",
                    "description": "Website resolves"
                },
                {
                    "title": "No",
                    "value": "nonResolver",
                    "description": "Website does not resolve"
                }
            ]
        }
    ]
}
```

We should document these specific XXX requirements in a separate TLD page, as we do for other TLDs. We should also inform the customer that for member ID changes they have to contact us as we don't currently expose this feature via API or UI.

**Comment by kayla-broussard** [comment]
@weppos I'm trying to work through the backlog of dnsimple-support issues - is there any additional information that needs to be included in a support article on this TLD?
