### ISSUE TITLE
Clarify that DNSSEC does not currently work with Secondary DNS services

### ISSUE THREAD

**Issue by onlyhavecans** [dnsimple/dnsimple-support#316]
Right now DNSSEC will not work correctly with AXFR transfers out. Documenting this better would help with support.

We might also want to put a warning when users try to enable one or the other when they already have one.

**Comment by aeden** [comment]
This is shown in the DNSSEC article. Is this sufficient to close this?

**Comment by kayla-broussard** [comment]
@onlyhavecans Can you take a peek at @aeden 's comment and let me know if any further changes should be made, or if this issue can be closed?

**Comment by onlyhavecans** [comment]
I think I is good as is now
