### ISSUE TITLE
EU and Brexit

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#431]
We need to have a support articles that explains what will happen to the .EU domains once Brexit will be into place.

This is what the EURid registry has published
https://eurid.eu/en/register-a-eu-domain/brexit-notice/

This is what Enom (our underlying registrar for .EU) sent to us:
https://www.enom.com/blog/what-brexit-means-for-eu-domain-owners-in-the-uk-2019/
https://mailchi.mp/0cf546a7c98e/important-uk-based-registrants-stand-to-lose-their-eu-domains

The article should have an introduction, and then outline the 2 scenarios with the key deadlines.

We'll send out an email as well to affected customers pointing to this document.

**Comment by weppos** [comment]
@itsalyse can I ask you to take care of the article? Feel free to ping me if you have specific or technical questions.

**Comment by aeden** [comment]
@weppos are you ok if we close this for now and reopen it in the future when there is movement in the UK/EU?
