### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#491]
https://travis-ci.org/dnsimple/dnsimple-support/jobs/625724721

```
All images optimized!
Publishing to S3
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v3.4.0/s3_website.jar into /home/travis/build/dnsimple/dnsimple-support/vendor/bundle/ruby/2.6.0/gems/s3_website-3.4.0/s3_website-3.4.0.jar
[fail] Could not load the site: Failed to parse ERB in /home/travis/build/dnsimple/dnsimple-support/s3_website.yml:
       (SyntaxError) /home/travis/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_warn.rb:15: syntax error, unexpected tLABEL
           module_function define_method(:warn) {|*messages, uplevel: nil|
                                                                    ^
Published
```

**Comment by weppos** [comment]
It looks like this is not a new issue, we got the same at https://github.com/dnsimple/dnsimple-support/pull/468

Underlying issue is https://github.com/laurilehmijoki/s3_website/issues/306

**Comment by weppos** [comment]
Outcome of this issue

- The build was not supposed to complete successfully
- Time may have come to consider an alternative publishing system, given the number of issues with the current one

**Comment by sbastn** [comment]
One alternative is using Travis to push to s3: https://docs.travis-ci.com/user/deployment We can also start using https://docs.travis-ci.com/user/deployment-v2 which they recommend at this point.
