### ISSUE TITLE
Fix table in Common DNS Records

### ISSUE THREAD

**Issue by SarahCaminiti1** [dnsimple/dnsimple-support#605]
<img width="765" alt="Screen Shot 2020-08-03 at 11 33 50 AM" src="https://user-images.githubusercontent.com/49121697/89199886-41376880-d57d-11ea-9d84-4b2abee60f93.png">

Very difficult to read

https://support.dnsimple.com/articles/common-dns-records/

**Comment by sbastn** [comment]
Duplicate of #603
