### ISSUE TITLE
Fix table on What is CNAME Record

### ISSUE THREAD

**Issue by SarahCaminiti1** [dnsimple/dnsimple-support#606]
https://support.dnsimple.com/articles/cname-record/

<img width="717" alt="Screen Shot 2020-08-03 at 11 35 47 AM" src="https://user-images.githubusercontent.com/49121697/89200080-852a6d80-d57d-11ea-99ce-f70b98566417.png">

**Comment by sbastn** [comment]
Duplicate of #603
