### ISSUE TITLE
Update layout of Difference Between A and CNAME Records

### ISSUE THREAD

**Issue by SarahCaminiti1** [dnsimple/dnsimple-support#612]
https://support.dnsimple.com/articles/differences-a-cname-records/

Can we space things out a little more here? Everything is clumped together and it makes it really tough to read

**Comment by dallasread** [comment]
@SarahCaminiti1 What do you think about adding subheadings to break it up a bit (eg. What are these records?, A Record, CNAME Record, How we use it)?

**Comment by SarahCaminiti1** [comment]
@dallasread I think that would make it look much better. Thank you!
