### ISSUE TITLE
Document the need to delete DS records when switching to DNSimple upon transfer

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#725]
When you transfer a domain to DNSimple, we sync the DS records and we do not alter the delegation.

However, if the user changes delegation to DNSimple and the zone is not signed, the DS record will conflict and cause the domain to stop resolving.

1. https://support.dnsimple.com/articles/transferring-domain/#after-the-transfer needs to be expanded. Where we instruct the customer to change the delegation, we must first add a point to review the DS records and remove them if the zone is not signed at DNSimple
2. https://support.dnsimple.com/articles/before-transferring-domain/ has a mention about ensuring there are no DS records, but it may use some additional warning formatting that explains existing DS record may cause the domain to stop resolving if you later on change delegation

**Comment by ggalmazor** [comment]
Adding a link to an important insight we need to somehow explain too: https://github.com/dnsimple/dnsimple-support/issues/657#issuecomment-763807209

**Comment by ggalmazor** [comment]
Maybe update this one too? https://dnsimple.com/how-to-transfer-without-downtime

**Comment by aeden** [comment]
> Maybe update this one too? https://dnsimple.com/how-to-transfer-without-downtime

Yes.

**Comment by deandre** [comment]
@aeden both PRs have been merged and this is now complete.
