### ISSUE TITLE
Improve 404 looks

### ISSUE THREAD

**Issue by OleMchls** [dnsimple/dnsimple-support#736]
Currently, we have no DNSimple branded 404 Page, but rather just the default Netlify one:

![Untitled](https://user-images.githubusercontent.com/584259/108177473-95fa9500-7103-11eb-8813-4376fdd38b60.jpg)

**Comment by aeden** [comment]
This should be done at the same time across all static sites.

**Comment by sbastn** [comment]
I expect the large majority of static sites to have a custom 404, for example: https://github.com/dnsimple/dnsimple-support/blob/main/content/404.markdown

These were configured in S3/Cloudfront. We're missing this configuration in Netlify.
