### ISSUE TITLE
"Using an SSL Certificate with Windows" article is out of date

### ISSUE THREAD

**Issue by jcaudle** [dnsimple/dnsimple-support#74]
The [Using and SSL Certificate with Windows](http://support.dnsimple.com/articles/ssl-certificate-with-windows/) page is out of date and even includes a dead link. I think it may be possible to replace this page with a new panel in the certificate installer wizard, but will need to do some research.

**Comment by jcaudle** [comment]
Komodo provides [a document about certificate installation on IIS 5.x and 6.x](https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/633/0/certificate-installation-microsoft-iis-5x--6x) and [another about what to do if you don't have root and intermediate certificates bundled with your primary certificate](https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/636/17/).

**Comment by weppos** [comment]
@jcaudle I believe the part we are missing here is the initial part where we describe the proper tasks to get a certificate for windows. As far as I know, IIS requires a custom CSR hence most of windows users purchase a cert with us and then they realize they have to request a reissue.

We probably need something a little bit more detailed on the pre-steps such as http://weblog.west-wind.com/posts/2014/May/08/IIS-SSL-Certificate-Renewal-Pain

**Comment by jcaudle** [comment]
It looks like it's possible to [import a PFX file even on IIS 5](https://www.trustico.jp/install/import/iis6/iis-import-pfx-ssl-instructions.php), but I'm not sure whether you need to export the CSR from the server or if you can use another CSR.

**Comment by jcaudle** [comment]
[Thawte provides an even more detailed guide](https://search.thawte.com/support/ssl-digital-certificates/index?page=content&id=SO5288).

**Comment by weppos** [comment]
@jcaudle what should we do here now that we have the PFX?
Also related to https://github.com/dnsimple/dnsimple-support/pull/173

**Comment by jcaudle** [comment]
This article needs to be updated to reflect the new wizard and there is a draft in the `article-stubs` branch.
