### ISSUE TITLE
Review claim about "redundancy and fallback" on A record article

### ISSUE THREAD

**Issue by ggalmazor** [dnsimple/dnsimple-support#807]
Re https://dnsimple.groovehq.com/tickets/123825

> Round robin doesn’t provide redundancy but load balancing, if one of the host is down, it will still redirect the traffic there, unless there is a way to verify that it is down.

**Comment by weppos** [comment]
The comment above is correct. However, the use of the term redundancy in the context of the article is also correct as well. You implement round robin adding multiple A record, with the result pointing a name to several _redundant_ machines.

We make no claim of automated failover, nor we imply any specially build DNSimple feature. That's a generic A record article. I think we can leave it as it is.
