### ISSUE TITLE
Display app status

### ISSUE THREAD

**Issue by sbastn** [dnsimple/dnsimple-support#88]
It might be interesting to display the current application status like we do on the application.
<img width="242" alt="screen shot 2015-10-08 at 9 45 53 am" src="https://cloud.githubusercontent.com/assets/80610/10360497/67f97c2c-6da1-11e5-9522-c28d36f38837.png">

**Comment by sbastn** [comment]
Maybe the landing page for support is a good place for it. We already have a link on the footer to the status page.

**Comment by aeden** [comment]
There is also a support article: http://localhost:3000/articles/dnsimple-status/

**Comment by sbastn** [comment]
This is for the scenario: "I am searching the docs because something is not quite right." I come to the landing page and see that the Name servers are down. Then I know that my issue might be related to that.

Real life example:
<img width="1187" alt="screen shot 2015-10-08 at 12 07 03 pm" src="https://cloud.githubusercontent.com/assets/80610/10363529/486297a4-6db5-11e5-9efc-c47f61328944.png">

**Comment by weppos** [comment]
Closing for now. Let's reopen if it becomes a concrete proposal.
