### ISSUE TITLE
Ratelimit is not at 0 but still returning 429

### ISSUE THREAD

**Issue by unreleased** [dnsimple/dnsimple-support#895]
Hello,

I've recently purchased this service and I've had a read through the documentation, in practice, I am using the domain availability API at https://api.dnsimple.com/v2/000000/registrar/domains/example.com/check

After about 70 requests of 200's I start to get constant 429s, despite the headers 

`X-RateLimit-Limit: 2400`
`X-RateLimit-Remaining: 2288`
`X-RateLimit-Reset: 1649814288`

Request ID:  e1c3db6f-33f1-462a-97d9-79390ac259c4

I'm not sure why this is happening and why it's returning 429s when I still have ratelimit quota remaining. The body shows:

```"message": "endpoint checkDomain quota exceeded"```

Kind regards.

**Comment by weppos** [comment]
Hello, certain endpoints have stricter limits to prevent abuse. Please reach out to support for more information.
