### ISSUE TITLE
Video about SSL Certificates and Let's Encrypt

### ISSUE THREAD

**Issue by SarahCaminiti1** [dnsimple/dnsimple-support#903]
To add to support documentation and you tube

Draft:
https://docs.google.com/document/d/12kJVX7wuF55JKGIFcM3zAuCP9r-UGRUJnno2mDtZdCY/edit

- [ ] Coming up with copy
- [ ] Validate
- [ ] Record voice
- [ ] Move to marketing 

- [ ] When video is done add it to support documentation

**Comment by weppos** [comment]
Closing as stale. We will reopen if planned.
